image: debian/stable
packages:
    - wget
sources:
    - https://github.com/go-kit/kit
tasks:
    - go_toolchain: |
        go_version="$(wget -q -O- https://golang.org/VERSION?m=text)"
        wget -q https://dl.google.com/go/$go_version.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf $go_version.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/go /usr/bin/go
        go env
    - dependencies: |
        mkdir -p $(go env GOPATH)/src/github.com/go-kit
        mv kit $(go env GOPATH)/src/github.com/go-kit
        go get -t github.com/go-kit/kit/...
    - test: |
        go test -race -v github.com/go-kit/kit/...
